module.exports = {
    ADMIN : 'ADMIN',
    TECHNICAL_ADMIN : 'TECHNICAL_ADMIN',
    PROJECT_MANAGER : 'PROJECT_MANAGER',
    FINANCIAL_OFFICER : 'FINANCIAL_OFFICER',
    BUDGET_AND_PROCUREMENT_MANAGER : 'BUDGET_PROCUREMENT_MANAGER'
}